#!/usr/bin/env python2
# -*- encoding: utf-8; py-indent-offset: 4 -*-


def agent_emcunity_arguments(params, hostname, ipaddress):
    args = ''

    if params.get("lockbox", False) == False:
        args += " -u " + quote_shell_string(params["username"])
        args += " -p " + quote_shell_string(params["password"][1])

    args += " " + quote_shell_string(ipaddress)
    return args

special_agent_info['emcunity'] = agent_emcunity_arguments
