#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Written/Edited by Philipp Näther
# philipp.naether@stadt-meissen.de

# 1:    ID             = spa
      # DPE            = dpe
      # Slot           = 0
      # Name           = SP A
      # Mode           = Normal
      # Health state   = OK (5)
      # Health details = "The component is operating normally. No action is required."
      # Model          = ASSY OBERON CANISTER 24GB 6C 85W
      # Part number    = 110-297-005C-06
      # Serial number  = CF2HK164400152
      # Memory size    = 25769803776 (24.0G)
      # Temperature    =

# 2:    ID             = spb
      # DPE            = dpe
      # Slot           = 1
      # Name           = SP B
      # Mode           = Normal
      # Health state   = OK (5)
      # Health details = "The component is operating normally. No action is required."
      # Model          = ASSY OBERON CANISTER 24GB 6C 85W
      # Part number    = 110-297-005C-06
      # Serial number  = CF2HK164400149
      # Memory size    = 25769803776 (24.0G)
      # Temperature    =

def inventory_emcunity_sp(info):
    for line in info:
        if re.match(".*Name.*", line[0]):
            item = line[1].lstrip()
            yield item, None

def check_emcunity_sp(item, params, info):
    i = 0
    for line in info:
        if info[i][1].lstrip() == item:
            mode = info[i+1][1].lstrip()
            hstate = info[i+2][1].lstrip()
            hdetail = info[i+3][1].lstrip()
            memsize = info[i+7][1].lstrip()
        i += 1
    return parse_emcstate(hstate), "%s, %s, Mode: %s, Memory Size: %s" % (hstate, hdetail, mode, memsize)

check_info["emcunity_sp"] = {
    'check_function'         :    check_emcunity_sp,
    'inventory_function'     :    inventory_emcunity_sp,
    'service_description'    :    'HW Storage Processor',
    'includes'               :    [ 'emcunity.include' ],
}
