#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Written/Edited by Philipp Näther
# philipp.naether@stadt-meissen.de

#<<<emcunity_cpu:sep(44)>>>
#2019-01-18 09:20:05,spa,19.51
#2019-01-18 09:20:05,spb,9.161

def inventory_emcunity_cpu(info):
    for line in info:
        item = line[1]
        yield item, None

def check_emcunity_cpu(item, params, info):
    for line in info:
        zone = line[1]
        util = line[2]
        if item == zone:
            return check_cpu_util(float(util), params)
            #check_temperature(float(temp), params, "emcunity_temp_%s" % item)

check_info["emcunity_cpu"] = {
    'check_function'         :    check_emcunity_cpu,
    'inventory_function'     :    inventory_emcunity_cpu,
    'service_description'    :    'CPU utilization %s',
    'has_perfdata'           :    True,
    'group'                  :    'cpu_utilization_multiitem',
    'includes'               :    [ 'cpu_util.include' ]
}
