#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# License: GNU General Public License v2

# Written/Edited by Philipp Näther
# philipp.naether@stadt-meissen.de
# andreas.doehler@gmail.com

# 1:    ID             = spa
      # DPE            = dpe
      # Slot           = 0
      # Name           = SP A
      # Mode           = Normal
      # Health state   = OK (5)
      # Health details = "The component is operating normally. No action is required."
      # Model          = ASSY OBERON CANISTER 24GB 6C 85W
      # Part number    = 110-297-005C-06
      # Serial number  = CF2HK164400152
      # Memory size    = 25769803776 (24.0G)
      # Temperature    =

# 2:    ID             = spb
      # DPE            = dpe
      # Slot           = 1
      # Name           = SP B
      # Mode           = Normal
      # Health state   = OK (5)
      # Health details = "The component is operating normally. No action is required."
      # Model          = ASSY OBERON CANISTER 24GB 6C 85W
      # Part number    = 110-297-005C-06
      # Serial number  = CF2HK164400149
      # Memory size    = 25769803776 (24.0G)
      # Temperature    =

def inventory_emcunity_sp(info):
    keys = None
    sps = emcunity_parse_info(info, keys)
    for sp in sps:
        item = sps[sp]["Name"]
        yield item, None


def check_emcunity_sp(item, params, info):
    keys = [ "Name", "Health state", "Health details", "Mode", "Memory size" ]
    sps = emcunity_parse_info(info, keys)
    for sp in sps:
        name = sps[sp]["Name"]
        if name == item:
            hstate = sps[sp]["Health state"]
            hdetail = sps[sp]["Health details"]
            mode = sps[sp]["Mode"]
            memsize = sps[sp]["Memory size"]
    return parse_emcstate(hstate), "%s, %s, Mode: %s, Memory Size: %s" % (hstate, hdetail, mode, memsize)


check_info["emcunity_sp"] = {
    'check_function'         :    check_emcunity_sp,
    'inventory_function'     :    inventory_emcunity_sp,
    'service_description'    :    'HW Storage Processor',
    'includes'               :    [ 'emcunity.include' ],
}
