#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Written/Edited by Philipp Näther
# philipp.naether@stadt-meissen.de

# 1:    ID                      = spb_iom_0_fc3
#       Name                    = SP B I/O Module 0 FC Port 3
#       SP                      = spb
#       WWN                     = 50:06:01:60:C7:E0:15:EA:50:06:01:6F:47:E0:15:EA
#       Speed                   =
#       Requested speed         =
#       Available speeds        = 4 Gbps, 8 Gbps, 16 Gbps, auto
#       Health state            = OK (5)
#       Health details          = "The port link is down, but not in use. No action is required."
#       Connector type          = LC
#       SFP supported speeds    = 4 Gbps, 8 Gbps, 16 Gbps
#       SFP supported protocols = FibreChannel
#       Replication capability  = RecoverPoint
#       SFP supported mode      = MultiMode
# 
# 2:    ID                      = spa_iom_0_fc1
#       Name                    = SP A I/O Module 0 FC Port 1
#       SP                      = spa
#       WWN                     = 50:06:01:60:C7:E0:15:EA:50:06:01:65:47:E0:15:EA
#       Speed                   = 16 Gbps
#       Requested speed         =
#       Available speeds        = 4 Gbps, 8 Gbps, 16 Gbps, auto
#       Health state            = OK (5)
#       Health details          = "The port is operating normally."
#       Connector type          = LC
#       SFP supported speeds    = 4 Gbps, 8 Gbps, 16 Gbps
#       SFP supported protocols = FibreChannel
#       Replication capability  = RecoverPoint
#       SFP supported mode      = MultiMode

def inventory_emcunity_fc(info):
# parse info, no key needed for inventory
# "Name" is automatically added
    keys = None
    fcs = emcunity_parse_info(info, keys)
    for fc in fcs:
        tokens = re.split(" ", fcs[fc]["Name"])
        item = "FC %s%s" % (tokens[1], tokens[-1])
        yield item, None

def check_emcunity_fc(item, params, info):
# parse info, just get data we want for this check by defining the keys
    keys = [ "Name", "Health state", "Health details", "Speed" ]
    fcs = emcunity_parse_info(info, keys)
    for fc in fcs:
        tokens = re.split(" ", fcs[fc]["Name"])
        name = "FC %s%s" % (tokens[1], tokens[-1])
        if name == item:
            hstate = fcs[fc]["Health state"]
            hdetail = fcs[fc]["Health details"]
            speed = fcs[fc]["Speed"]
    return parse_emcstate(hstate), "%s, %s, Speed: %s" % (hstate, hdetail, speed)

check_info["emcunity_fc"] = {
    'check_function'         :    check_emcunity_fc,
    'inventory_function'     :    inventory_emcunity_fc,
    'service_description'    :    'Interface %s',
    'includes'               :    [ 'emcunity.include' ],
}
