#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# License: GNU General Public License v2

# Written/Edited by Philipp Näther
# philipp.naether@stadt-meissen.de
# andreas.doehler@gmail.com

# <<<emcunity_general>>>
# 1:    System name             = EMCVM
#       Model                   = Unity 300
#       Platform type           = EMC Storage System
#       Product serial number   = CKM00164500882
#       Auto failback           = on
#       Health state            = OK (5)
#       Health details          = "The system is operating normally."
#       Power (Present)         = 347 watts
#       Power (Rolling Average) = 347 watts
#       Supported SP upgrades   = SP400, SP500, SP600

def inventory_emcunity_general(info):
    for line in info:
        if re.match(".*System name.*", line[0]):
            item = line[1]
            yield item, None


def check_emcunity_general(item, params, info):
    for line in info:
        if re.match(".*Model.*", line[0]):
            model = line[1]
        elif re.match("Health state", line[0]):
            hstate = line[1]
        elif re.match("Health detail", line[0]):
           hdetail = line[1]

    return parse_emcstate(hstate), "%s - %s %s" % (model, hstate, hdetail)


check_info["emcunity_general"] = {
    'check_function'         :    check_emcunity_general,
    'inventory_function'     :    inventory_emcunity_general,
    'service_description'    :    'System %s',
    'includes'               :    [ 'emcunity.include' ],
}
