#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Written/Edited by Philipp Näther
# philipp.naether@stadt-meissen.de

# 1:    ID                            = dpe
      # Slot                          = 0
      # Name                          = DPE
      # Health state                  = OK (5)
      # Health details                = "The component is operating normally. No action is required."
      # Manufacturer                  =
      # Model                         = OBERON 25DRV 24GB 6C 85W 1.6G
      # Part number                   = 100-542-921-10
      # Serial number                 = CKM00164502222
      # Power (Present)               = 351 watts
      # Power (Rolling Average)       = 349 watts
      # Temperature                   = 66° F (19° C)
      # Temperature (Present)         = 66° F (19° C)
      # Temperature (Rolling Average) = 66° F (19° C)

def inventory_emcunity_dpe(info):
# parse info, no key needed for inventory
# "Name" is automatically added
    keys = None
    dpes = emcunity_parse_info(info, keys)
    for dpe in dpes:        
        item = dpes[dpe]["Name"]
        yield item, None

def check_emcunity_dpe(item, params, info):
# parse info, just get data we want for this check by defining the keys
    keys = [ "Name", "Health state", "Health details", "Power (Present)" ]
    dpes = emcunity_parse_info(info, keys)
    for dpe in dpes:
        name = dpes[dpe]["Name"]
        if name == item:
            hstate = dpes[dpe]["Health state"]
            hdetail = dpes[dpe]["Health details"]
            pwr = dpes[dpe]["Power (Present)"]            
    return parse_emcstate(hstate), "%s, %s, Power: %s" % (hstate, hdetail, pwr)

check_info["emcunity_dpe"] = {
    'check_function'         :    check_emcunity_dpe,
    'inventory_function'     :    inventory_emcunity_dpe,
    'service_description'    :    'HW Disk Processor Enclosure',
    'includes'               :    [ 'emcunity.include' ],
}
