#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# License: GNU General Public License v2

# Written/Edited by Philipp Näther
# philipp.naether@stadt-meissen.de
# andreas.doehler@gmail.com

# 1:    ID             = dpe_ps_a0
      # Enclosure      = dpe
      # SP             = spa
      # Slot           = 0
      # Name           = DPE Power Supply A0
      # Health state   = OK (5)
      # Health details = "The component is operating normally. No action is required."
      # Manufacturer   = ACBEL POLYTECH INC.
      # Model          = 12V P/S WITH 12VSTBY AND FAN
      # Part number    = 071-000-611-01
      # Serial number  = AC7N9163703102

# 2:    ID             = dpe_ps_b0
      # Enclosure      = dpe
      # SP             = spb
      # Slot           = 0
      # Name           = DPE Power Supply B0
      # Health state   = OK (5)
      # Health details = "The component is operating normally. No action is required."
      # Manufacturer   = ACBEL POLYTECH INC.
      # Model          = 12V P/S WITH 12VSTBY AND FAN
      # Part number    = 071-000-611-01
      # Serial number  = AC7N9163702302

def inventory_emcunity_pwrsupply(info):
    keys = None
    psus = emcunity_parse_info(info, keys)
    for psu in psus:
        tokens = re.split(" ", psus[psu]["Name"])
        item = "PSU " + tokens[3]
        yield item, None


def check_emcunity_pwrsupply(item, params, info):
    keys = [ "Name", "Health state", "Health details" ]
    psus = emcunity_parse_info(info, keys)
    for psu in psus:
        tokens = re.split(" ", psus[psu]["Name"])
        name = "PSU " + tokens[3]
        if name == item:
            hstate = psus[psu]["Health state"]
            hdetail = psus[psu]["Health details"]
    return parse_emcstate(hstate), "%s, %s" % (hstate, hdetail)


check_info["emcunity_pwrsupply"] = {
    'check_function' : check_emcunity_pwrsupply,
    'inventory_function' : inventory_emcunity_pwrsupply,
    'service_description' : 'HW',
    'includes' : [ 'emcunity.include' ],
}
