#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Written/Edited by Philipp Näther
# philipp.naether@stadt-meissen.de

# <<<emcunity_general>>>
# 1:    System name             = EMCVM
#       Model                   = Unity 300
#       Platform type           = EMC Storage System
#       Product serial number   = CKM00164500882
#       Auto failback           = on
#       Health state            = OK (5)
#       Health details          = "The system is operating normally."
#       Power (Present)         = 347 watts
#       Power (Rolling Average) = 347 watts
#       Supported SP upgrades   = SP400, SP500, SP600

def inventory_emcunity_general(info):
    for line in info:
        if re.match(".*System name.*", line[0]):
            item = line[1]
            yield item, None

def check_emcunity_general(item, params, info):
    for line in info:
        if re.match(".*Model.*", line[0]):
            model = line[1]
        elif re.match("Health state", line[0]):
            hstate = line[1]
        elif re.match("Health detail", line[0]):
           hdetail = line[1]
    return parse_emcstate(hstate), "%s - %s %s" % (model, hstate, hdetail)

check_info["emcunity_general"] = {
    'check_function'         :    check_emcunity_general,
    'inventory_function'     :    inventory_emcunity_general,
    'service_description'    :    '',
    'includes'               :    [ 'emcunity.include' ],
}
