#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Written/Edited by Philipp Näther
# philipp.naether@stadt-meissen.de

# 1:    ID             = dpe_ps_a0
      # Enclosure      = dpe
      # SP             = spa
      # Slot           = 0
      # Name           = DPE Power Supply A0
      # Health state   = OK (5)
      # Health details = "The component is operating normally. No action is required."
      # Manufacturer   = ACBEL POLYTECH INC.
      # Model          = 12V P/S WITH 12VSTBY AND FAN
      # Part number    = 071-000-611-01
      # Serial number  = AC7N9163703102

# 2:    ID             = dpe_ps_b0
      # Enclosure      = dpe
      # SP             = spb
      # Slot           = 0
      # Name           = DPE Power Supply B0
      # Health state   = OK (5)
      # Health details = "The component is operating normally. No action is required."
      # Manufacturer   = ACBEL POLYTECH INC.
      # Model          = 12V P/S WITH 12VSTBY AND FAN
      # Part number    = 071-000-611-01
      # Serial number  = AC7N9163702302

def inventory_emcunity_pwrsupply(info):
    for line in info:
        if re.match(".*Name.*", line[0]):
            tokens = re.split(" ", line[1].lstrip())
            item = "PSU " + tokens[3]
            yield item, None

def check_emcunity_pwrsupply(item, params, info):
    i = 0
    for line in info:
        tokens = re.split(" ", info[i][1].lstrip())
        if len(tokens) >= 4:
            line = "PSU " + tokens[3]
            if line == item:
                hstate = info[i+1][1].lstrip()
                hdetail = info[i+2][1].lstrip()
        i += 1
    return parse_emcstate(hstate), "%s, %s" % (hstate, hdetail)

check_info["emcunity_pwrsupply"] = {
    'check_function' : check_emcunity_pwrsupply,
    'inventory_function' : inventory_emcunity_pwrsupply,
    'service_description' : 'HW',
    'includes' : [ 'emcunity.include' ],
}
